# Generated by Django 4.0.1 on 2022-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_desc', models.TextField(max_length=500)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='College',
            field=models.CharField(choices=[('Carlos Hilado Memorial State College, Binalbagan', 'Carlos Hilado Memorial State College, Binalbagan'), ('Carlos Hilado Memorial State College, Talisay', 'Carlos Hilado Memorial State College, Talisay'), ('Carlos Hilado Memorial State College, Fortune Town', 'Carlos Hilado Memorial State College, Fortune Town'), ('Carlos Hilado Memorial State College, Alijis', 'Carlos Hilado Memorial State College, Alijis')], default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
