# Generated by Django 4.0.1 on 2022-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_events_alter_user_college_alter_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_college',
            new_name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='College',
            field=models.CharField(choices=[('DharmSinh Desai University,Nadiad', 'DharmSinh Desai University,Nadiad')], default='None', max_length=80),
        ),
    ]
