# Generated by Django 4.0.1 on 2022-04-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_rename_is_college_user_is_admin_alter_user_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_college',
        ),
    ]
